version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
